In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('pedidos_narashop.csv', sep=';')
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3
...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18

In [7]:
df['valor_pedido'] = df['quantidade'] * df['valor_unitario']
df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_pedido
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4,87.67
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18,197.10

#### O gerente quer saber quais categorias geraram mais receita. 
#### Apresente o faturamento total por categoria, do maior para o menor.

In [8]:
df_total_categoria = df.groupby('categoria')['valor_pedido'].sum().reset_index()
df_total_categoria.sort_values(by='valor_pedido', ascending=False, inplace= True)
df_total_categoria

          categoria  valor_pedido
2       Eletrônicos   37037997.65
3          Esportes    8058234.35
1  Casa e Decoração    3333395.06
0        Brinquedos    2306126.65

03 -

In [11]:
df_entregue_acima_500 = df.loc[(df['status_pedido'] == 'Entregue') & (df['valor_pedido'] > 500)]

df_entregue_acima_500II = df.query('status_pedido == "Entregue"' and 'valor_pedido > 500')
df_entregue_acima_500II

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_pedido
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
5,10006,Diego Fernandes,Esportes,Bicicleta Ergométrica,Em trânsito,2,1326.21,8,2652.42
10,10011,Simone Castro,Eletrônicos,Notebook,Em trânsito,1,3522.09,9,3522.09
...,...,...,...,...,...,...,...,...,...
19993,29994,Rafael Oliveira,Eletrônicos,Notebook,Em trânsito,1,5237.04,10,5237.04
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36

04 -

In [18]:
df_produto = df.groupby('produto')['valor_pedido'].sum().reset_index()
df_produto.sort_values(by='valor_pedido', ascending=False, inplace=True)
df_produto.head()

                  produto  valor_pedido
27               Notebook   15091721.74
37               Smart TV    8474171.95
38             Smartphone    6806241.19
1   Bicicleta Ergométrica    5949159.26
40                 Tablet    3258725.63

In [19]:
array_valor_produto = np.array(df_produto['valor_pedido'])
q1 = np.percentile(array_valor_produto, 25)
q3 = np.percentile(array_valor_produto, 75)
print(q1)
print(q3)

73869.3475
367550.645

In [20]:
df_produto_25_mais = df_produto.loc[df_produto['valor_pedido'] > q3]
df_produto_25_mais

                  produto  valor_pedido
27               Notebook   15091721.74
37               Smart TV    8474171.95
38             Smartphone    6806241.19
1   Bicicleta Ergométrica    5949159.26
40                 Tablet    3258725.63
39             Smartwatch    1344856.80
13   Fritadeira Air Fryer     980636.15
17        Jogo de Panelas     760544.58
36            SSD Externo     719921.59
45       Tênis de Corrida     696912.40
44    Telescópio Infantil     409588.10
43       Teclado Mecânico     372827.72

In [21]:
df_produto_25_menos = df_produto.loc[df_produto['valor_pedido'] < q1]
df_produto_25_menos

                     produto  valor_pedido
0          Bermuda Esportiva      73266.61
8        Conjunto de Toalhas      70889.32
6        Carregador Portátil      64156.00
14           Garrafa Térmica      63532.51
10         Difusor de Aromas      57532.21
34  Quebra-Cabeça 1000 peças      51701.41
30                   Pelúcia      51088.67
42            Tapete de Yoga      50209.91
28    Organizador de Gavetas      36586.33
32            Porta-Retratos      26224.38
9             Corda de Pular      23767.20
24       Massinha de Modelar      17550.06

06 -

In [23]:
array_valor_pedido = np.array(df['valor_pedido'])
media = np.mean(array_valor_pedido)
mediana = np.median(array_valor_pedido)
distancia = (media - mediana) / mediana

print(f'A média é de {media}\nA Mediana é de {mediana}')
print(f'A distância entre a Média e a Mediana é de {distancia:.2%}')

A média é de 2536.7876855
A Mediana é de 882.635
A distância entre a Média e a Mediana é de 187.41%